# Generated by Django 5.2 on 2026-05-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('desc', models.CharField(max_length=500, verbose_name='desc')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('date', models.CharField(max_length=20, verbose_name='date')),
            ],
        ),
    ]
